### PR TITLE
bug fix - making player invulnerable as soon as he spawns

### LINKED ISSUE #15: Spaceship is losing health after spawning if there is an asteroid already at the spawn position
Give it a small time interval after spawning before it can be hit by a asteroid. 
Make it blink in that time interval

### PR DESCRIPTION
**Pull request by desai10**
This PR fixes #15

### CODE REVIEW

**Comment by desai10** [comment]
@j-tesla so what I have done is tracked when the player spawns. And 1 second after he spawns, he will be flickering to indicate he is invulnerable and during this time he will not take any damage either! Please let me know if this approach is fine with you, also let me know if the invulnerable time has to be changed.

**Comment by j-tesla** [comment]
@desai10 that's almost perfect. One small doubt about the flickering effect implementation: You moved the ship below the screen to hide it in the flickering right? When I shoot when the ship is below the screen the bullets spawn below the screen. I suggest that we make change in the shoot method of the the Player class: Instead of spawning at `self.rect.top`, we can spawn at a reference height. This solves that issue I guess.
The issue is not at all noticeable in that short time, but I thought may we'll notice it in some future edits.

Also it looks better if we lower the flickering frequency and increase the invulnerability time at least 2 seconds.

**Comment by desai10** [comment]
Yaa sure, makes sense! I'll add a commit to address these things now.

**Comment by desai10** [comment]
@j-tesla I added a commit to address those 2 items (flicker interval and bullet spawn position). Please have a look and let me know if this is fine.

**Comment by j-tesla** [comment]
@desai10 What I meant about lowering flickering frequency is making it look more like blinking, like in all games. Rest of the changes are perfect.

**Comment by desai10** [comment]
Sorry, I don't think I understand... So you want the player to fade in and fade out?

**Comment by j-tesla** [comment]
@desai10 you didn't get me. :sweat_smile: I'll just make a commit.

**Comment by desai10** [comment]
ohh sorry!
Thank you! :)

**Pull request merged**
