### PR TITLE
adding menu

### LINKED ISSUE #2: Add Menu
Instead of directly starting the game on start, add a menu.

### LINKED ISSUE #4: Change font
retro style is preferable

### PR DESCRIPTION
**Pull request by 95ych**
Added menu , also added instructions
Changed font

Closes #2  Closes #4

### CODE REVIEW

**Comment by 95ych** [comment]
resolves #2 and #4
@j-tesla

**Comment by 95ych** [comment]
ok lemme change then

**Comment by 95ych** [comment]
resolved @j-tesla

**Comment by j-tesla** [comment]
now LGTM :v:

**Pull request merged**
