### PR TITLE
add menu button at game over

### PR DESCRIPTION
**Pull request by codephile1221**
This PR will close issue #30 opened by me.
I have added a button labelled "MENU" which, on clicked, will take the user back to the main menu.

There is a slight "bug" though. The previous state of the Mobs is continued . However, it is not a major problem and its only effect is the illusion that the user starts where they left off.

### CODE REVIEW

**Comment by codephile1221** [comment]
hello, 
I've added the necessary style changes too.

https://github.com/j-tesla/space-shooter/pull/32/commits/f8446216bc7177011ee0ebaf4262de73b07cf81e
This is the original commit ^

**Comment by codephile1221** [comment]
Are you planning on merging the PR or is it unsatisfactory?

**Comment by j-tesla** [comment]
> Are you planning on merging the PR or is it unsatisfactory?

I thought to figure out a way to fix that bug about mobs. I am not at all free at this time, so I kept it on hold.

**Comment by codephile1221** [comment]
Maybe I'll give it a shot later. I'm busy atm too.

Have you tried running my fork? Perhaps if you experience the bug, you will understand what I mean better.

**Comment by codephile1221** [comment]
Maybe I'll give it a shot later. I'm busy atm, too.

@j-tesla , Have you tried running my fork? Perhaps if you experience the bug, you will understand what I mean better.

**Comment by j-tesla** [comment]
I didn't run it yet, but I understood wat you said.

**Comment by j-tesla** [comment]
@codephile1221 nvm, I fixed it. Next time before you work on a feature, please make sure your commits are on top of the master branch of the parent repo. (in this case my repo) I had to do two merges manually which would have been one 'merge PR'. :sweat_smile: just to skip this trouble

**Pull request merged**
